# Site settings
name: Marcel Neeleman
author: Marcel Neeleman
title: Marcel Neeleman
email: neeleman@mpia.de
description: Marcel Neeleman. Resume and Research in Astronomy and Astrophysics while at UCSD, UCSC and MPIA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
